# .github/workflows/docker-build.yml
name: Docker Build

on:
  push:
    branches:
      - dev
env:
  DOCKER_IMAGE_NAME: magamanex/github-action-demo
  DOCKER_IMAGE_TAG: dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Create .env file dynamically (optional, if not already committed)
      - name: Generate .env File
        run: |
          cat <<EOF > .env
          NEXT_ENV=$NEXT_ENV
          NEXT_PUBLIC_BEWALLET_BACKEND_URL=$NEXT_PUBLIC_BEWALLET_BACKEND_URL
          NEXT_PUBLIC_API_KEY=$NEXT_PUBLIC_API_KEY
          NEXT_PUBLIC_ANALYTICS_ID=$NEXT_PUBLIC_ANALYTICS_ID 
          NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
          NEXT_PUBLIC_FEATURE_FLAG=$NEXT_PUBLIC_FEATURE_FLAG 
          EOF
        env:
          NEXT_ENV: "test"
          NEXT_PUBLIC_BEWALLET_BACKEND_URL: "test"
          NEXT_PUBLIC_API_KEY: "test"
          NEXT_PUBLIC_ANALYTICS_ID: "test"
          NEXT_PUBLIC_APP_NAME: "test"
          NEXT_PUBLIC_FEATURE_FLAG: "test"

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .

      - name: Publish Docker Image
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
