# .github/workflows/docker-build.yml
name: Docker Build

on:
  push:
    branches:
      - dev
env:
  DOCKER_IMAGE_TAG: github-action-demo:dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Create .env file dynamically (optional, if not already committed)
      - name: Create .env File
        run: |
          echo "MY_SECRET_KEY=${{ secrets.DOCKER_USERNAME }}" > .env

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE_TAG .

      - name: Publish Docker Image
        run: |
          docker push $DOCKER_IMAGE_TAG

